services:
  postgres:
    restart: always
    ports: []  # Закрываем внешние порты

  rabbitmq:
    restart: always
    ports: []  # Закрываем внешние порты в продакшене

  balance-service:
    build:
      context: ./services/balance-service
      dockerfile: Dockerfile
      target: production
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-admin}:${RABBITMQ_PASSWORD:-password}@rabbitmq:5672
    ports: []  # Закрываем внешние порты в продакшене
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner  # Используем финальный этап сборки
    restart: always
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-admin}:${RABBITMQ_PASSWORD:-password}@rabbitmq:5672
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      nextjs:
        condition: service_healthy
    restart: always
    networks:
      - app_network
