services:
  postgres:
    ports:
      - "${DATABASE_PORT}:5432"  # Открываем порт для доступа извне

  pgadmin:
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - app_network

  rabbitmq:
    ports:
      - "5672:5672"   # AMQP протокол
      - "15672:15672" # Веб-интерфейс управления
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-password}

  balance-service:
    build:
      context: ./services/balance-service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./services/balance-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq
