services:
  postgres:
    restart: always
    ports: []  # Закрываем внешние порты

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner  # Используем финальный этап сборки
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs
    restart: always
    networks:
      - app_network
