import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import { AuthProvider, SeedMock } from "@core/components/business";

import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ul>
          <li><Link href='/profile'>profile</Link></li>
          <li><Link href='/events'>events</Link></li>
          <li><Link href='/balance/withdraw'>withdraw</Link></li>
          <li><Link href='/balance/deposit'>deposit</Link></li>
          <li><Link href='/auth/signup'>signup</Link></li>
        </ul>
        <SeedMock />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
