name: Deploy to Dev Server

# Запускается при пуше в ветку dev
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Чекаут кода
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка SSH ключа для доступа к серверу
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.secret_working_key }}
        known_hosts: 141.95.17.102

    # Деплой на сервер
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@141.95.17.102 '
          cd ~ &&
          cd unie &&
          git pull origin dev &&
          docker compose down &&
          sudo docker compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.production up --force-recreate -v -d --build
        '

    # Опционально: очистка неиспользуемых образов
    - name: Clean up Docker
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@141.95.17.102 '
          docker system prune -f
        '
      if: always()
